//! velos-gpu: GPU device management, compute dispatch, and rendering.
//! Exposes high-level API only -- no raw wgpu types in public API.

pub mod app;
pub mod buffers;
pub mod camera;
pub mod orbit_camera;
pub mod lighting;
pub mod lod;
pub mod mesh_loader;
pub mod renderer3d;
pub mod road_surface;
pub mod compute;
mod compute_wave_front;
pub mod device;
pub mod ped_adaptive;
pub mod perception;
pub mod error;
pub mod multi_gpu;
pub mod partition;
pub mod map_tiles;
pub mod renderer;
pub mod sim;
pub mod sim_startup;
pub mod cpu_reference;
mod sim_helpers;
mod sim_junction;
mod sim_mobil;
mod sim_lifecycle;
pub mod sim_render;
mod sim_bus;
pub mod sim_meso;
mod sim_pedestrians;
mod sim_perception;
mod sim_signals;
mod sim_vehicles;
mod sim_calibration;
mod sim_reroute;
pub mod sim_snapshot;

pub use app::VelosApp;
pub use buffers::{BufferPool, GpuKinematics, GpuPosition};
pub use camera::Camera2D;
pub use compute::ComputeDispatcher;
pub use ped_adaptive::{GpuPedestrian, PedestrianAdaptiveParams, PedestrianAdaptivePipeline};
pub use perception::{PerceptionBindings, PerceptionParams, PerceptionPipeline, PerceptionResult};
pub use device::GpuContext;
pub use error::GpuError;
pub use map_tiles::{MapTileRenderer, TileVertex};
pub use renderer::{AgentInstance, Renderer};
pub use orbit_camera::{OrbitCamera, ViewMode, ViewTransition, MeshInstance3D, BillboardInstance3D};
pub use lighting::{compute_lighting, LightingUniform};
pub use lod::{classify_lod, LodTier};
pub use mesh_loader::{load_glb, LoadedMesh, MeshSet, Vertex3D};
pub use renderer3d::Renderer3D;
pub use road_surface::{RoadSurfaceVertex, JunctionData, generate_road_mesh, generate_lane_markings, generate_junction_surfaces};
